# Adapted from https://github.com/r-lib/actions/blob/v2-branch/examples/bookdown.yaml
#
# Deployment app: https://github.com/JamesIves/github-pages-deploy-action

on:
  push:
    branches: [main, master]

name: bookdown

jobs:
  bookdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-renv@v2
      
      - name: Cache results
        uses: actions/cache@v3
        with:
          path: pages
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Install dependencies
        run: install.packages("bookdown")
        shell: Rscript {0}

      - name: Build
        run: lapply(list.files("./pages/", pattern = "^.+\\.Rmd$", full.names = TRUE), rmarkdown::render, output_dir="./docs/")
        shell: Rscript {0}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: main
          folder: pages
          target-folder: pages
